#' The instance's About page
#'
#' The wikibase.cloud hosting policy expects the main page or `Project:About` to
#' say what the instance is for, and disqualifies instances holding data about
#' living people without local rules for it. This instance holds person items
#' for authors and codecheckers, so the page says both: what the instance is,
#' and what it does and does not record about people.
#'
#' @param generated_at the timestamp to stamp the page with
#' @return the page's wikitext
#' @keywords internal
wikibase_about_wikitext <- function(generated_at = Sys.time()) {
  c(
    "This page is generated by <code>codecheck::bootstrap_wikibase()</code> and is",
    "overwritten by every run. Do not edit it by hand.",
    "",
    "== What this instance is ==",
    "",
    "[https://codecheck.org.uk/ CODECHECK] is a process for the independent execution",
    "of the computations underlying a scholarly paper. A codechecker runs the authors'",
    "code, records what was needed to make it run and what came out, and publishes the",
    "result as a citable certificate with a DOI. Every check carried out is listed in",
    "the [https://codecheck.org.uk/register/ CODECHECK Register].",
    "",
    "This Wikibase holds the register as linked data: one item per certificate, per",
    "checked paper, per codechecker and per venue, so that a check can be queried and",
    "cited like any other scholarly object rather than only read as a web page. See",
    "[[Project:Data model]] for the properties and class items,",
    "[[Project:Certificates]] for the certificates themselves, and",
    "[[Project:Example queries]] for SPARQL to ask the record questions with, on",
    "Wikidata and here.",
    "",
    "== Who it is for ==",
    "",
    "It is a staging instance for contributing CODECHECK data to the Wikidata and",
    "Wikibase ecosystem: a place to develop and review the deposition code, and to",
    "show reviewers and the wider community what the certificates look like as linked",
    "data before they reach Wikidata. The export to Wikidata itself is a separate,",
    "manual step, never a write from here: [[Project:Wikidata export]] shows its",
    "state &mdash; which certificates and checked works have items there, and the",
    "batches that created them.",
    "",
    "The audience is therefore anyone interested in the record of reproducibility",
    "checks in scholarly publishing &mdash; researchers, journals and infrastructure",
    "projects &mdash; and the Wikidata community reviewing the proposed modelling.",
    "The modelling decisions and the reasoning behind them are discussed in the open",
    "at [https://github.com/codecheckers/register/issues/50 register#50].",
    "",
    "== Where the content comes from ==",
    "",
    "Everything on this instance is generated from the register's",
    "<code>register.csv</code> and the data model in the",
    "[https://github.com/codecheckers/codecheck codecheck R package], and can be",
    "rebuilt from an empty wiki at any time. '''Nothing lives only here.''' The",
    "register is the authority; do not record anything on this instance that exists",
    "nowhere else.",
    "",
    "The instance mints its own property and item numbers, so <code>P31</code> here is",
    "not Wikidata's <code>P31</code>. Every entity carries a \"Wikidata entity\"",
    "statement naming its counterpart.",
    "",
    "== Personal data ==",
    "",
    "The instance holds items for living people: the authors of checked papers and",
    "the codecheckers who checked them. The rules for that content are:",
    "",
    paste("* Only public scholarly identity is recorded &mdash; the name as published and, where",
          "given, the ORCID. No contact details, affiliation history, or any other personal",
          "information is stored."),
    paste("* Everything comes from the already-public CODECHECK Register and the",
          "<code>codecheck.yml</code> files of the checks themselves, which the people concerned",
          "took part in publishing. Nothing is inferred, scraped or merged from elsewhere."),
    paste("* Person items are generated, not curated: they are recreated from the register on",
          "every load, so a correction has to be made in the register to persist."),
    paste("* Corrections and removal requests go to the register at",
          "[https://github.com/codecheckers/register/issues codecheckers/register] or to the",
          "maintainers via [https://codecheck.org.uk/ codecheck.org.uk]. A change there reaches",
          "this instance with the next load."),
    "",
    "== Who maintains it ==",
    "",
    "The CODECHECK team, in the open, at",
    "[https://github.com/codecheckers/codecheck codecheckers/codecheck] (the code)",
    "and [https://github.com/codecheckers/register codecheckers/register] (the data).",
    "Contact details are on [https://codecheck.org.uk/ codecheck.org.uk]; issues on",
    "either repository reach the maintainers.",
    "",
    "See [[Project:Copyrights]] for licensing.",
    "",
    paste0("Generated ", format(generated_at, "%Y-%m-%d %H:%M:%S %Z"), "."),
    ""
  )
}

#' The instance's Copyrights page
#'
#' The hosting policy requires the licensing statement to be visible on
#' `Project:Copyrights`. The register's data is under ODC-BY rather than CC0, so
#' the page states that rather than asserting a waiver nobody has granted, and
#' says why the individual statements are nonetheless freely reusable.
#'
#' @param generated_at the timestamp to stamp the page with
#' @return the page's wikitext
#' @keywords internal
wikibase_copyright_wikitext <- function(generated_at = Sys.time()) {
  c(
    "This page is generated by <code>codecheck::bootstrap_wikibase()</code> and is",
    "overwritten by every run. Do not edit it by hand.",
    "",
    "== Structured data ==",
    "",
    "The items, properties and statements on this instance are derived from the",
    "[https://codecheck.org.uk/register/ CODECHECK Register], whose database is",
    "published under the",
    "[https://opendatacommons.org/licenses/by/summary/ Open Data Commons Attribution",
    "License (ODC-BY)].",
    "",
    "The individual statements are bare facts &mdash; identifiers, DOIs, dates,",
    "titles, ORCIDs and the links between them &mdash; and facts are not subject to",
    "copyright. ODC-BY covers the register '''as a database''', and its attribution",
    "requirement is met by naming the CODECHECK Register as the source; every",
    "certificate item on this instance links back to its register entry and to its",
    "report DOI, so a reuser is handed that attribution with the data.",
    "",
    "This instance is a derived, disposable staging copy rather than a publication of",
    "the database in its own right: it is regenerated from the register on every run",
    "and may be rebuilt from empty at any time. See [[Project:About]].",
    "",
    "== Text ==",
    "",
    "The generated pages in the Project namespace are produced by the",
    "[https://github.com/codecheckers/codecheck codecheck R package], which is",
    "published under the [https://opensource.org/licenses/MIT MIT License].",
    "",
    "Both licenses permit commercial and non-commercial use and the creation of",
    "derivative works.",
    "",
    "== The checks themselves ==",
    "",
    "A CODECHECK certificate is a separate publication with its own DOI, deposited",
    "under [https://creativecommons.org/licenses/by/4.0/ CC BY 4.0]. The certificate",
    "items here describe those reports; they do not reproduce them. The checked",
    "papers are the work of their own authors under their own terms, and are referred",
    "to here only by identifier.",
    "",
    "== Authority ==",
    "",
    "The register is authoritative for licensing as it is for everything else: where",
    "this page and",
    "[https://github.com/codecheckers/register#license the register's own statement]",
    "disagree, the register wins. Licensing questions go to the maintainers via",
    "[https://codecheck.org.uk/ codecheck.org.uk] or the",
    "[https://github.com/codecheckers/register/issues register issue tracker].",
    "",
    paste0("Generated ", format(generated_at, "%Y-%m-%d %H:%M:%S %Z"), "."),
    ""
  )
}


#' The instance's Main Page
#'
#' The front door, and the one page that used to be written by hand - which is
#' how it came to miss pages generated after it. The list of where to look is
#' built from [WIKIBASE_PAGES], so a page added there is listed here too.
#'
#' @param generated_at the timestamp to stamp the page with
#' @return the page's wikitext
#' @keywords internal
wikibase_main_wikitext <- function(generated_at = Sys.time()) {
  listed <- Filter(function(page) !is.null(page$description), WIKIBASE_PAGES)
  c(
    "__NOTOC__",
    "[https://codecheck.org.uk/ CODECHECK] is a process for the independent execution",
    "of the computations underlying a scholarly paper. A codechecker runs the authors'",
    "code on their own machine, records what was needed to make it run and what came",
    "out, and publishes the result as a citable certificate with a DOI. Every check that",
    "has been carried out is listed in the",
    "[https://codecheck.org.uk/register/ CODECHECK Register].",
    "",
    "This Wikibase holds the register as linked data: one item per certificate, per",
    "checked paper, per codechecker and per venue, so that a check can be queried and",
    "cited like any other scholarly object rather than only read as a web page. It is a",
    "staging instance &mdash; a place to test the deposition code and to show the result",
    "before it reaches Wikidata, where the certificates and the works they check have",
    "items of their own. '''Nothing lives only here.''' Everything on this instance is",
    "generated from the register and the data model, and can be rebuilt from an empty",
    "wiki at any time, so do not record anything here that exists nowhere else.",
    "",
    "The instance mints its own property and item numbers, so <code>P31</code> here is",
    "not Wikidata's <code>P31</code>. Every entity therefore carries a \"Wikidata",
    "entity\" statement naming its counterpart.",
    "",
    "== Where to look ==",
    "",
    vapply(listed, function(page) paste0("* [[", page$title, "]] &mdash; ", page$description),
           character(1), USE.NAMES = FALSE),
    paste("* [https://codecheck.org.uk/ codecheck.org.uk] &mdash; the project website: what a",
          "CODECHECK is, how to request one, and how to become a codechecker."),
    paste("* [https://codecheck.org.uk/register/ The CODECHECK Register] &mdash; the",
          "authoritative list of all certificates, and the source this instance is generated from."),
    "",
    "== How this is maintained ==",
    "",
    "This page, and every page listed above, is generated by the",
    "[https://github.com/codecheckers/codecheck codecheck R package] from the register's",
    "data and the data model, and overwritten by",
    "<code>codecheck::publish_wikibase_pages()</code>. Do not edit them by hand. The",
    "modelling decisions, and the reasoning behind them, are discussed in",
    "[https://github.com/codecheckers/register/issues/50 register#50].",
    "",
    paste0("Generated ", format(generated_at, "%Y-%m-%d %H:%M:%S %Z"), "."),
    ""
  )
}

#' The wikitext of one generated page
#'
#' The generator for every page in [WIKIBASE_PAGES], in one place, so that a
#' page in the registry without one is an error rather than a page nobody
#' writes.
#'
#' @param key a name of [WIKIBASE_PAGES]
#' @param context what the generators need, see [wikibase_page_context()]; a
#'   page that needs nothing from it does not touch it
#' @return the page's wikitext, one line per element
#' @keywords internal
wikibase_page_wikitext <- function(key, context = NULL) {
  switch(key,
    main = wikibase_main_wikitext(),
    about = wikibase_about_wikitext(),
    copyrights = wikibase_copyright_wikitext(),
    copyright_redirect = paste0("#REDIRECT [[", WIKIBASE_PAGES$copyrights$title, "]]"),
    data_model = wikibase_report_wikitext(context$plan),
    example_queries = wikibase_examples_wikitext(context$plan),
    certificates = wikibase_certificates_wikitext(context$written,
                                                  context$records$certificates,
                                                  context$register_qids),
    wikidata_export = wikidata_preview_wikitext(context$preview,
                                                context$records$certificates,
                                                attr(context$preview, "batches"),
                                                submitted = context$submitted,
                                                register_qids = context$register_qids),
    stop("No generator for the Wikibase page '", key, "'")
  )
}

#' What the page generators need, fetched only when a page asks for it
#'
#' Each value is a promise: publishing only the Main Page reads nothing, while
#' the Wikidata export page resolves every certificate against Wikidata. A caller
#' that already holds a value - the bootstrap its plan, the load what it wrote -
#' assigns it over the promise.
#'
#' @param dir the register repository
#' @param session a session from [wikibase_session()], or `NULL` to read
#'   anonymously
#' @param log_file the edit log, or `NULL` for the `codecheck.wikibase_log`
#'   option
#' @param method how to resolve against Wikidata, see [preview_wikidata_export()]
#' @return an environment
#' @keywords internal
wikibase_page_context <- function(dir = "../register", session = NULL,
                                  log_file = NULL, method = "search") {
  context <- new.env(parent = emptyenv())
  handle <- if (is.null(session)) NULL else session$handle
  delayedAssign("records", read_register_records(dir), assign.env = context)
  delayedAssign("mapping", wikibase_mapping(session), assign.env = context)
  delayedAssign("plan", wikibase_plan_local_ids(plan_wikibase_entities(context$mapping),
                                                context$mapping),
                assign.env = context)
  delayedAssign("written", wikibase_loaded_entities(context$records, context$mapping, handle),
                assign.env = context)
  delayedAssign("preview", wikidata_export_plan(context$records, method = method),
                assign.env = context)
  delayedAssign("submitted", wikidata_submitted_batches(log_file), assign.env = context)
  delayedAssign("register_qids", read_register_wikidata(dir), assign.env = context)
  context
}

#' The certificates and checked works the instance holds, as the load reports them
#'
#' What [load_wikibase_register()] returns about the entities it wrote,
#' rebuilt from the instance itself, so the certificate index can be written
#' without loading anything.
#'
#' @param records the output of [read_register_records()]
#' @param mapping the output of [wikibase_mapping()]
#' @param handle an optional `httr` handle
#' @return a `data.frame` with columns `kind`, `key`, `action` and `id`, one row
#'   per paper and certificate found on the instance
#' @keywords internal
wikibase_loaded_entities <- function(records, mapping, handle = NULL) {
  local <- stats::setNames(mapping$local_id, mapping$wikidata_id)
  local <- as.list(local[!is.na(names(local))])
  index <- wikibase_identifier_index(local, handle)
  rows <- wikibase_export_rows(records)

  found <- lapply(c("paper", "certificate"), function(kind) {
    keys <- unique(wikibase_key_column(rows[[kind]], kind))
    keys <- keys[!is.na(keys)]
    property <- WIKIDATA_MODEL[[kind]]$resolve$property
    ids <- unname(index[paste0(property, "=", keys)])
    data.frame(kind = rep(kind, length(keys)), key = keys, action = rep("exists", length(keys)),
               id = ids, stringsAsFactors = FALSE)[!is.na(ids), , drop = FALSE]
  })
  out <- do.call(rbind, found)
  rownames(out) <- NULL
  out
}

#' The certificates' Wikidata items as the register records them
#'
#' `register.json` does not carry the column, so it is read from `register.csv`
#' directly, skipping the commented-out rows the file holds.
#'
#' @param dir the register repository holding `register.csv`
#' @return a named character vector, certificate ID to QID, only for the
#'   certificates that have one; empty when there is no register or no column
#' @keywords internal
read_register_wikidata <- function(dir) {
  none <- stats::setNames(character(0), character(0))
  path <- file.path(dir, "register.csv")
  if (!file.exists(path)) return(none)
  lines <- readLines(path, warn = FALSE)
  lines <- lines[!grepl("^\\s*(#|$)", lines)]
  if (length(lines) < 2) return(none)
  table <- utils::read.csv(text = lines, colClasses = "character", check.names = FALSE)
  if (!all(c("Certificate", WIKIDATA_REGISTER_COLUMN) %in% names(table))) return(none)
  qids <- table[[WIKIDATA_REGISTER_COLUMN]]
  keep <- !is.na(qids) & grepl("^Q[0-9]+$", qids)
  stats::setNames(qids[keep], table$Certificate[keep])
}

#' The QuickStatements batches recorded as run on Wikidata
#'
#' @param log_file the edit log, or `NULL` for the `codecheck.wikibase_log`
#'   option
#' @return the log rows of the submitted Wikidata batches, oldest first
#' @keywords internal
wikidata_submitted_batches <- function(log_file = NULL) {
  log <- wikibase_log_read(log_file)
  submitted <- log[which(log$target == "wikidata" & log$status == "submitted"), , drop = FALSE]
  rownames(submitted) <- NULL
  submitted
}

#' The current text of pages on the instance
#'
#' @param handle an `httr` handle, or `NULL` to read anonymously
#' @param titles the page titles
#' @return a character vector named by title, `NA` for a page that does not
#'   exist
#' @keywords internal
wikibase_page_content <- function(handle, titles) {
  out <- stats::setNames(rep(NA_character_, length(titles)), titles)
  for (chunk in split(titles, ceiling(seq_along(titles) / 50))) {
    pages <- wikibase_get(handle, list(
      action = "query", prop = "revisions", rvprop = "content", rvslots = "main",
      titles = paste(chunk, collapse = "|"), formatversion = 2
    ))$query$pages
    for (page in pages) {
      content <- page$revisions[[1]]$slots$main$content
      if (!is.null(content) && page$title %in% titles) out[[page$title]] <- content
    }
  }
  out
}

#' Whether a generated page would say anything new
#'
#' Every generated page ends in a "Generated ..." timestamp, so a rewrite always
#' differs from what is there. Comparing without it keeps a rerun from adding a
#' revision that changes nothing but the time.
#'
#' @param current the page as it is, `NA` if it does not exist
#' @param text the page as it would be written
#' @return `TRUE` if writing `text` would change nothing but the timestamp
#' @keywords internal
wikibase_page_unchanged <- function(current, text) {
  if (length(current) != 1 || is.na(current)) return(FALSE)
  strip <- function(x) {
    lines <- strsplit(paste(x, collapse = "\n"), "\n", fixed = TRUE)[[1]]
    # MediaWiki trims the whitespace a page ends in when it saves it
    sub("\\s+$", "", paste(lines[!grepl("^Generated .*\\.$", lines)], collapse = "\n"))
  }
  identical(strip(current), strip(text))
}

#' Write generated pages onto the instance
#'
#' The one place a page is written, whichever function generated it. A page
#' whose content has not changed is left alone, see [wikibase_page_unchanged()].
#'
#' @param session a session from [wikibase_session()]; `NULL` with `dry_run`
#' @param texts a named list, [WIKIBASE_PAGES] key to the page's wikitext
#' @param summary the edit summary
#' @param log_file the edit log, or `NULL` for the `codecheck.wikibase_log`
#'   option
#' @param dry_run if `TRUE` compare with the instance and write nothing
#' @return a `data.frame` with the `page` key, its `title` and its `status`:
#'   `"written"`, `"unchanged"`, `"would create"` or `"would update"`,
#'   invisibly
#' @keywords internal
write_wikibase_pages <- function(session, texts, summary, log_file = NULL,
                                 dry_run = FALSE) {
  unknown <- setdiff(names(texts), names(WIKIBASE_PAGES))
  if (length(unknown) > 0) stop("Not a generated Wikibase page: ", paste(unknown, collapse = ", "))
  titles <- vapply(names(texts), function(key) WIKIBASE_PAGES[[key]]$title, character(1),
                   USE.NAMES = FALSE)
  handle <- if (is.null(session)) NULL else session$handle
  current <- wikibase_page_content(handle, titles)

  status <- character(length(texts))
  for (i in seq_along(texts)) {
    text <- paste(texts[[i]], collapse = "\n")
    url <- wikibase_page_url(titles[i])
    if (wikibase_page_unchanged(current[[titles[i]]], text)) {
      status[i] <- "unchanged"
      cli::cli_alert_info("Unchanged: {.url {url}}")
      next
    }
    if (dry_run) {
      status[i] <- if (is.na(current[[titles[i]]])) "would create" else "would update"
      cli::cli_alert("Would write {.url {url}}")
      next
    }
    wikibase_post(session, list(
      action = "edit",
      title = titles[i],
      text = text,
      summary = summary,
      bot = 1
    ), what = paste0("page '", titles[i], "'"))
    wikibase_log(target = "wikibase", action = "edit", kind = "page", id = titles[i],
                 label = names(texts)[i], status = "done", file = log_file)
    status[i] <- "written"
    cli::cli_alert_success("Written: {.url {url}}")
  }

  invisible(data.frame(page = names(texts), title = titles, status = status,
                       stringsAsFactors = FALSE))
}

#' A page's address on the instance
#'
#' @param title the page title
#' @return the URL
#' @keywords internal
wikibase_page_url <- function(title) {
  paste0(WIKIBASE_INSTANCE$url, "/wiki/", gsub(" ", "_", title, fixed = TRUE))
}

#' Rewrite the generated pages on the CODECHECK Wikibase
#'
#' Each page is otherwise written only as a side effect of the step it belongs
#' to - the bootstrap, the load, the preview of the Wikidata export - and says
#' what was true when that step last ran. This rebuilds them all from the
#' register and the instance as they are now, so the pages can be brought up to
#' date without repeating any of those steps; in the register, `make wikibase`.
#'
#' Reads the register's rendered `docs/register.json` (render first) and
#' `register.csv`, the instance, and - for the Wikidata export page - Wikidata
#' itself. Writes only pages, never items, and only the pages whose content has
#' changed.
#'
#' @param dir the register repository
#' @param pages the pages to write, names of the package's page registry
#'   (`"main"`, `"about"`, `"copyrights"`, `"copyright_redirect"`,
#'   `"data_model"`, `"example_queries"`, `"certificates"`,
#'   `"wikidata_export"`); `NULL`, the default, for all of them
#' @param dry_run if `TRUE` (the default) report which pages would change
#'   without writing; a real run needs `WIKIBASE_USER` and `WIKIBASE_TOKEN`
#' @param log_file the edit log, or `NULL` for the `codecheck.wikibase_log`
#'   option; the Wikidata export page lists the batches it records as run
#' @param method how to resolve against Wikidata, see [preview_wikidata_export()]
#' @return a `data.frame` with one row per page and its status, invisibly
#' @examples
#' \dontrun{
#' publish_wikibase_pages("../register")                   # what would change
#' publish_wikibase_pages("../register", dry_run = FALSE)  # write it
#' }
#' @export
publish_wikibase_pages <- function(dir = "../register", pages = NULL, dry_run = TRUE,
                                   log_file = NULL, method = c("search", "sparql")) {
  method <- match.arg(method)
  pages <- pages %||% names(WIKIBASE_PAGES)
  unknown <- setdiff(pages, names(WIKIBASE_PAGES))
  if (length(unknown) > 0) {
    stop("Unknown page(s): ", paste(unknown, collapse = ", "), ". Known: ",
         paste(names(WIKIBASE_PAGES), collapse = ", "))
  }
  cli::cli_h2("Publishing the CODECHECK Wikibase pages{if (dry_run) ' (dry run)' else ''}")

  session <- if (dry_run) NULL else wikibase_session()
  context <- wikibase_page_context(dir, session, log_file = log_file, method = method)
  texts <- lapply(stats::setNames(pages, pages), wikibase_page_wikitext, context = context)
  result <- write_wikibase_pages(session, texts,
                                 summary = "generated by codecheck::publish_wikibase_pages()",
                                 log_file = log_file, dry_run = dry_run)

  if (dry_run) cli::cli_alert_info("Dry run, nothing written. Pass {.code dry_run = FALSE} to write it.")
  invisible(result)
}
