#' The instance's About page
#'
#' The wikibase.cloud hosting policy expects the main page or `Project:About` to
#' say what the instance is for, and disqualifies instances holding data about
#' living people without local rules for it. This instance holds person items
#' for authors and codecheckers, so the page says both: what the instance is,
#' and what it does and does not record about people.
#'
#' @param generated_at the timestamp to stamp the page with
#' @return the page's wikitext
#' @keywords internal
wikibase_about_wikitext <- function(generated_at = Sys.time()) {
  c(
    "This page is generated by <code>codecheck::bootstrap_wikibase()</code> and is",
    "overwritten by every run. Do not edit it by hand.",
    "",
    "== What this instance is ==",
    "",
    "[https://codecheck.org.uk/ CODECHECK] is a process for the independent execution",
    "of the computations underlying a scholarly paper. A codechecker runs the authors'",
    "code, records what was needed to make it run and what came out, and publishes the",
    "result as a citable certificate with a DOI. Every check carried out is listed in",
    "the [https://codecheck.org.uk/register/ CODECHECK Register].",
    "",
    "This Wikibase holds the register as linked data: one item per certificate, per",
    "checked paper, per codechecker and per venue, so that a check can be queried and",
    "cited like any other scholarly object rather than only read as a web page. See",
    "[[Project:Data model]] for the properties and class items, and",
    "[[Project:Certificates]] for the certificates themselves.",
    "",
    "== Who it is for ==",
    "",
    "It is a staging instance for contributing CODECHECK data to the Wikidata and",
    "Wikibase ecosystem: a place to develop and review the deposition code, and to",
    "show reviewers and the wider community what the certificates look like as linked",
    "data, before certificates are created on Wikidata itself. What such an export",
    "would do is shown on [[Project:Wikidata export]]; nothing has been sent to",
    "Wikidata from here.",
    "",
    "The audience is therefore anyone interested in the record of reproducibility",
    "checks in scholarly publishing &mdash; researchers, journals and infrastructure",
    "projects &mdash; and the Wikidata community reviewing the proposed modelling.",
    "The modelling decisions and the reasoning behind them are discussed in the open",
    "at [https://github.com/codecheckers/register/issues/50 register#50].",
    "",
    "== Where the content comes from ==",
    "",
    "Everything on this instance is generated from the register's",
    "<code>register.csv</code> and the data model in the",
    "[https://github.com/codecheckers/codecheck codecheck R package], and can be",
    "rebuilt from an empty wiki at any time. '''Nothing lives only here.''' The",
    "register is the authority; do not record anything on this instance that exists",
    "nowhere else.",
    "",
    "The instance mints its own property and item numbers, so <code>P31</code> here is",
    "not Wikidata's <code>P31</code>. Every entity carries a \"Wikidata entity\"",
    "statement naming its counterpart.",
    "",
    "== Personal data ==",
    "",
    "The instance holds items for living people: the authors of checked papers and",
    "the codecheckers who checked them. The rules for that content are:",
    "",
    "* Only public scholarly identity is recorded &mdash; the name as published and,",
    "  where given, the ORCID. No contact details, affiliation history, or any other",
    "  personal information is stored.",
    "* Everything comes from the already-public CODECHECK Register and the",
    "  <code>codecheck.yml</code> files of the checks themselves, which the people",
    "  concerned took part in publishing. Nothing is inferred, scraped or merged from",
    "  elsewhere.",
    "* Person items are generated, not curated: they are recreated from the register",
    "  on every load, so a correction has to be made in the register to persist.",
    "* Corrections and removal requests go to the register at",
    "  [https://github.com/codecheckers/register/issues codecheckers/register] or to",
    "  the maintainers via [https://codecheck.org.uk/ codecheck.org.uk]. A change",
    "  there reaches this instance with the next load.",
    "",
    "== Who maintains it ==",
    "",
    "The CODECHECK team, in the open, at",
    "[https://github.com/codecheckers/codecheck codecheckers/codecheck] (the code)",
    "and [https://github.com/codecheckers/register codecheckers/register] (the data).",
    "Contact details are on [https://codecheck.org.uk/ codecheck.org.uk]; issues on",
    "either repository reach the maintainers.",
    "",
    "See [[Project:Copyrights]] for licensing.",
    "",
    paste0("Generated ", format(generated_at, "%Y-%m-%d %H:%M:%S %Z"), "."),
    ""
  )
}

#' The instance's Copyrights page
#'
#' The hosting policy requires the licensing statement to be visible on
#' `Project:Copyrights`. The register's data is under ODC-BY rather than CC0, so
#' the page states that rather than asserting a waiver nobody has granted, and
#' says why the individual statements are nonetheless freely reusable.
#'
#' @param generated_at the timestamp to stamp the page with
#' @return the page's wikitext
#' @keywords internal
wikibase_copyright_wikitext <- function(generated_at = Sys.time()) {
  c(
    "This page is generated by <code>codecheck::bootstrap_wikibase()</code> and is",
    "overwritten by every run. Do not edit it by hand.",
    "",
    "== Structured data ==",
    "",
    "The items, properties and statements on this instance are derived from the",
    "[https://codecheck.org.uk/register/ CODECHECK Register], whose database is",
    "published under the",
    "[https://opendatacommons.org/licenses/by/summary/ Open Data Commons Attribution",
    "License (ODC-BY)].",
    "",
    "The individual statements are bare facts &mdash; identifiers, DOIs, dates,",
    "titles, ORCIDs and the links between them &mdash; and facts are not subject to",
    "copyright. ODC-BY covers the register '''as a database''', and its attribution",
    "requirement is met by naming the CODECHECK Register as the source; every",
    "certificate item on this instance links back to its register entry and to its",
    "report DOI, so a reuser is handed that attribution with the data.",
    "",
    "This instance is a derived, disposable staging copy rather than a publication of",
    "the database in its own right: it is regenerated from the register on every run",
    "and may be rebuilt from empty at any time. See [[Project:About]].",
    "",
    "== Text ==",
    "",
    "The generated pages in the Project namespace are produced by the",
    "[https://github.com/codecheckers/codecheck codecheck R package], which is",
    "published under the [https://opensource.org/licenses/MIT MIT License].",
    "",
    "Both licenses permit commercial and non-commercial use and the creation of",
    "derivative works.",
    "",
    "== The checks themselves ==",
    "",
    "A CODECHECK certificate is a separate publication with its own DOI, deposited",
    "under [https://creativecommons.org/licenses/by/4.0/ CC BY 4.0]. The certificate",
    "items here describe those reports; they do not reproduce them. The checked",
    "papers are the work of their own authors under their own terms, and are referred",
    "to here only by identifier.",
    "",
    "== Authority ==",
    "",
    "The register is authoritative for licensing as it is for everything else: where",
    "this page and",
    "[https://github.com/codecheckers/register#license the register's own statement]",
    "disagree, the register wins. Licensing questions go to the maintainers via",
    "[https://codecheck.org.uk/ codecheck.org.uk] or the",
    "[https://github.com/codecheckers/register/issues register issue tracker].",
    "",
    paste0("Generated ", format(generated_at, "%Y-%m-%d %H:%M:%S %Z"), "."),
    ""
  )
}

#' Write the hosting-policy pages onto the instance
#'
#' `Project:About` and `Project:Copyrights` are what the wikibase.cloud hosting
#' policy asks every hosted instance for, and a rebuilt instance has to be
#' compliant without a manual step, so they are written like the generated index
#' pages rather than curated by hand. `Project:Copyright`, MediaWiki's own
#' footer target, is left as a redirect to the plural.
#'
#' @param session a session from [wikibase_session()]
#' @return the page titles, invisibly
#' @keywords internal
write_wikibase_policy_pages <- function(session) {
  pages <- list(
    list(title = WIKIBASE_INSTANCE$about_page,
         text = paste(wikibase_about_wikitext(), collapse = "\n")),
    list(title = WIKIBASE_INSTANCE$copyright_page,
         text = paste(wikibase_copyright_wikitext(), collapse = "\n")),
    list(title = WIKIBASE_INSTANCE$copyright_redirect,
         text = paste0("#REDIRECT [[", WIKIBASE_INSTANCE$copyright_page, "]]"))
  )

  for (page in pages) {
    wikibase_post(session, list(
      action = "edit",
      title = page$title,
      text = page$text,
      summary = "generated by codecheck::bootstrap_wikibase()",
      bot = 1
    ), what = paste0("page '", page$title, "'"))
  }

  invisible(vapply(pages, function(page) page$title, character(1)))
}
